import { Category, Collection, FAQItem, GalleryItem, Product, SiteSettings, Testimonial } from "./types";

export const initialSiteSettings: SiteSettings = {
  brand_name: "artbythread.7",
  tagline_primary: "Made by Thread. Made with Heart.",
  tagline_secondary: "Little pieces of handmade happiness, created one thread at a time.",
  whatsapp_number: "+919265047933",
  whatsapp_default_message: "Hi ArtByThread.7! I visited your website and would love to know more about your handmade creations.",
  instagram_url: "https://instagram.com/artbythread.7",
  instagram_username: "@artbythread.7",
  email_contact: "henviparekh@gmail.com",
  announcement_banner_text: "✨ Accepting custom handmade requests for upcoming occasions. Handcrafted with love.",
  announcement_banner_enabled: true,
  meta_title: "ArtByThread.7 | Handmade Thread Art, Handkerchief Embroidery & Bespoke Gifts",
  meta_description: "Artisanal thread studio crafting bespoke handkerchief embroidery, everlasting crochet flower bouquets, custom keychains, and personalized gifts. Handcrafted with heart, one thread at a time.",
  location_text: "Handcrafted in India • Shipping Nationwide",
  making_time_default: "3 to 6 days handcrafting time",
  hero_headline_line1: "Made by Thread.",
  hero_headline_line2: "Made with Heart.",
  hero_subheading: "Handcrafted creations, thoughtful gifts and little pieces of art made especially for you.",
  updated_at: new Date().toISOString(),
};

export const initialCategories: Category[] = [
  {
    id: "cat-1",
    slug: "handkerchiefs",
    name: "Handkerchief Embroidery",
    tagline: "Personalized hand-stitched cotton handkerchiefs",
    description: "Bespoke hand embroidery on pure cotton handkerchiefs — custom logos, line art, dates, and sentiment messages.",
    image_url: "/products/handkerchief-iloveu-embroidery.jpg",
    order: 1,
  },
  {
    id: "cat-2",
    slug: "bouquets",
    name: "Handmade Bouquets",
    tagline: "Everlasting floral arrangements",
    description: "Curated everlasting bouquets wrapped in luxury craft paper, tied with natural silk ribbons.",
    image_url: "/products/orchid-bouquet-never-fades.jpg",
    order: 2,
  },
  {
    id: "cat-3",
    slug: "flowers",
    name: "Crochet Flowers",
    tagline: "Blooms that never wither or fade",
    description: "Soft, tactile single stems and floral clusters handcrafted in premium milk cotton yarn.",
    image_url: "/products/red-rose-black-wrap.jpg",
    order: 3,
  },
  {
    id: "cat-4",
    slug: "keychains",
    name: "Keychains & Charms",
    tagline: "A gentle touch of art in your pocket",
    description: "Compact woven and embroidered letter keychains, custom names, and sunflower charms.",
    image_url: "/products/kgt-crochet-keychain.jpg",
    order: 4,
  },
  {
    id: "cat-5",
    slug: "custom",
    name: "Custom Creations",
    tagline: "Your imagination brought to life",
    description: "Have a unique photo, logo, color palette, or milestone? Let us stitch a one-of-a-kind heirloom piece for you.",
    image_url: "/products/handkerchief-bmw-embroidery.jpg",
    order: 5,
  },
];

export const initialCollections: Collection[] = [
  {
    id: "col-1",
    slug: "embroidered-handkerchiefs",
    name: "Handkerchief Embroidery",
    tagline: "Thoughtful keepsake handkerchiefs hand-stitched with love",
    description: "Personalized initial handkerchiefs, custom line art portraits, and logo embroidery.",
    image_url: "/products/handkerchief-iloveu-embroidery.jpg",
    product_ids: ["prod-1", "prod-2"],
    is_featured: true,
  },
  {
    id: "col-2",
    slug: "forever-flowers",
    name: "Forever Flowers",
    tagline: "Eternal blooms that keep memories fresh forever",
    description: "Our signature crochet botanical collection featuring roses, orchids, and custom floral bouquets.",
    image_url: "/products/orchid-bouquet-never-fades.jpg",
    product_ids: ["prod-3", "prod-4"],
    is_featured: true,
  },
  {
    id: "col-3",
    slug: "alphabet-keychains",
    name: "Handmade Keychains",
    tagline: "Sweet, thoughtful tokens made with genuine heart",
    description: "Charming pocket keychains, initial letters, custom name keychains, and sunflower charms.",
    image_url: "/products/kgt-crochet-keychain.jpg",
    product_ids: ["prod-5", "prod-6"],
    is_featured: true,
  },
];

export const initialProducts: Product[] = [
  // ─── 1. HANDKERCHIEF EMBROIDERY (I LOVE YOU LINE ART) ───────────────────────
  {
    id: "prod-1",
    slug: "couples-line-art-embroidered-handkerchief",
    name: "Couples Line Art Embroidered Handkerchief",
    category: "handkerchiefs",
    collection_id: "col-1",
    short_description: "Hand-embroidered couple hug line art on pure white cotton handkerchief with pink french knots & 'I LOVE U' sentiment border.",
    description: "A keepsake made to be cherished forever. Handcrafted on pure white cotton handkerchief fabric, featuring delicate black thread line art of a couple embrace, accented with miniature pink French knot flowers and an 'I LOVE U' embroidered ribbon border. Soft, personal, and profoundly romantic — the perfect anniversary or wedding gift.",
    price: 650,
    is_available: true,
    is_featured: true,
    is_bestseller: true,
    is_new: true,
    is_published: true,
    images: [
      {
        id: "img-1-1",
        url: "/products/handkerchief-iloveu-embroidery.jpg",
        alt: "Hand-embroidered couple hug line art handkerchief with I LOVE U sentiment border",
        is_primary: true,
        order: 1,
      },
      {
        id: "img-1-2",
        url: "/products/handkerchief-bmw-embroidery.jpg",
        alt: "Custom logo embroidered handkerchief alternate style",
        is_primary: false,
        order: 2,
      },
    ],
    materials: ["100% Pure White Cotton Handkerchief", "DMC Colorfast Embroidery Floss", "Hand-stitched Satin Ribbon"],
    dimensions: "30 cm x 30 cm",
    making_time: "2-4 business days",
    care_instructions: "Gentle cold hand wash. Iron on reverse with a cotton pressing cloth.",
    customization_options: "Custom line art drawing, initials, date, or personalized romantic message.",
    shipping_info: "Dispatched in a parchment gift envelope with custom wax seal.",
    story: "Stitched to capture intimate moments of warmth and unconditional love.",
    tags: ["Handkerchief", "Embroidery", "Couples Gift", "I Love You", "Anniversary"],
    created_at: "2025-02-15T10:00:00Z",
    updated_at: "2025-02-25T10:00:00Z",
  },

  // ─── 2. HANDKERCHIEF EMBROIDERY (BMW LOGO + BELL KEYCHAIN) ──────────────────
  {
    id: "prod-2",
    slug: "custom-logo-embroidered-handkerchief-set",
    name: "Custom Logo Embroidered Handkerchief Set",
    category: "handkerchiefs",
    collection_id: "col-1",
    short_description: "Bespoke BMW logo hand-stitched in tight chain stitches on pure white cotton handkerchief, paired with a metal bell keychain.",
    description: "Showcase your passion or gift a car enthusiast something truly unique. Features a meticulously hand-embroidered BMW emblem in black and royal blue cotton thread on crisp white cotton fabric, paired with an antique metal bell keychain attachment. Fully customizable with any car logo, personal monogram, or initial.",
    price: 750,
    is_available: true,
    is_featured: true,
    is_bestseller: false,
    is_new: true,
    is_published: true,
    images: [
      {
        id: "img-2-1",
        url: "/products/handkerchief-bmw-embroidery.jpg",
        alt: "Custom BMW logo hand-embroidered cotton handkerchief with metal bell keychain",
        is_primary: true,
        order: 1,
      },
    ],
    materials: ["100% Cotton Handkerchief", "Black & Blue Cotton Floss", "Metal Bell Keyring"],
    dimensions: "30 cm x 30 cm",
    making_time: "3-4 business days",
    care_instructions: "Gentle hand wash only.",
    customization_options: "Choose any car logo, brand emblem, or personal monogram.",
    shipping_info: "Eco-friendly craft box wrapping.",
    story: "Combining functional cotton craft with bespoke personal identity.",
    tags: ["Handkerchief", "Logo Embroidery", "BMW", "Custom Gift", "Handmade"],
    created_at: "2025-02-16T10:00:00Z",
    updated_at: "2025-02-25T10:00:00Z",
  },

  // ─── 3. HANDMADE BOUQUET ───────────────────────────────────────────────────
  {
    id: "prod-3",
    slug: "pastel-dream-forever-bouquet",
    name: "A Bouquet That Never Fades",
    category: "bouquets",
    collection_id: "col-2",
    short_description: "Handmade with love. Soft crochet orchids, daisies & lilac blooms wrapped in silk gold ribbon — a timeless gift for birthdays, anniversaries, or just because.",
    description: "Not just a bouquet — it's a feeling. Every petal is hand-crocheted in soft milk cotton yarn, individually shaped and wired for graceful posture. Wrapped elegantly in ivory parchment with gold satin ribbon, this arrangement features white orchid blooms, lilac flowers, and deep plum accents. A soft, unique, thoughtfully crafted gift that stays beautiful forever.",
    price: 1650,
    is_available: true,
    is_featured: true,
    is_bestseller: true,
    is_new: false,
    is_published: true,
    images: [
      {
        id: "img-3-1",
        url: "/products/orchid-bouquet-never-fades.jpg",
        alt: "Crochet orchid and daisy bouquet wrapped in ivory parchment and gold ribbon",
        is_primary: true,
        order: 1,
      },
    ],
    materials: ["5-ply Milk Cotton Yarn", "Floral Craft Wire", "Recycled Craft Wrap", "Cotton Ribbon"],
    dimensions: "Approx. 32 cm height x 20 cm width",
    making_time: "3-5 business days",
    care_instructions: "Do not machine wash. If dusty, gently blow with cool hairdryer setting.",
    customization_options: "Choose your flower combinations (Orchids, Roses, Daisies, Lilac).",
    shipping_info: "Dispatched in a reinforced tall box.",
    story: "Created because fresh flowers wither in days, but the feeling of being cherished deserves to last a lifetime.",
    tags: ["Crochet Bouquet", "Forever Flowers", "Pastel", "Gift For Her", "Anniversary"],
    created_at: "2025-01-18T10:00:00Z",
    updated_at: "2025-02-22T10:00:00Z",
  },

  // ─── 4. SINGLE STEM ROSE ──────────────────────────────────────────────────
  {
    id: "prod-4",
    slug: "crimson-rose-single-stem",
    name: "Crimson Rose — Single Stem Crochet",
    category: "flowers",
    collection_id: "col-2",
    short_description: "A hand-crocheted deep red rose with green leaf, wrapped in a dramatic black parchment cone with gold tape — the ultimate romantic single stem.",
    description: "Bold. Romantic. Timeless. A single crimson crochet rose with a wired green leaf, accompanied by delicate sprigs of baby's breath. Wrapped in an elegant black parchment cone sealed with gold washi tape — this is the handmade equivalent of a luxury florist's rose.",
    price: 320,
    is_available: true,
    is_featured: true,
    is_bestseller: false,
    is_new: true,
    is_published: true,
    images: [
      {
        id: "img-4-1",
        url: "/products/red-rose-black-wrap.jpg",
        alt: "Crimson crochet rose wrapped in black parchment cone with gold tape",
        is_primary: true,
        order: 1,
      },
    ],
    materials: ["Soft Milk Cotton Yarn", "Steel Floral Wire", "Hypoallergenic Fiberfill"],
    dimensions: "28 cm stem length, 6 cm bloom height",
    making_time: "2-3 business days",
    care_instructions: "Spot clean with damp cloth if needed. Keep indoors.",
    customization_options: "Available in Crimson Red, Peach Blush, Butter Yellow, Baby Pink, and Cream White.",
    shipping_info: "Individually wrapped with a mini bow.",
    story: "The red rose represents deep passion, devotion, and timeless love.",
    tags: ["Single Stem", "Rose", "Desk Decor", "Under 500", "Handmade"],
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2025-02-23T10:00:00Z",
  },

  // ─── 5. CUSTOM NAME / INITIAL CROCHET KEYCHAIN (KGT) ──────────────────────
  {
    id: "prod-5",
    slug: "custom-name-crochet-keychain",
    name: "Custom Name / 3-Letter Crochet Keychain (e.g. KGT)",
    category: "keychains",
    collection_id: "col-3",
    short_description: "100% handmade 3-letter custom name or initial keychain (e.g. KGT) in pastel blue crochet yarn with a white daisy accent & silver ring.",
    description: "Spell your name or your initials in handcrafted crochet yarn. Handcrafted letter by letter (e.g. 'KGT', 'HARSH', 'DREAM') in soft pastel blue cotton yarn with a delicate white daisy accent. Comes attached to a sturdy silver keyring. Fully customizable in letter combination and color palette.",
    price: 420,
    is_available: true,
    is_featured: true,
    is_bestseller: true,
    is_new: true,
    is_published: true,
    images: [
      {
        id: "img-5-1",
        url: "/products/kgt-crochet-keychain.jpg",
        alt: "KGT custom 3-letter crochet name keychain held in hand with white daisy accent",
        is_primary: true,
        order: 1,
      },
      {
        id: "img-5-2",
        url: "/products/alphabet-keychain-template.jpg",
        alt: "Crochet alphabet keychain template showing all A-Z letters",
        is_primary: false,
        order: 2,
      },
    ],
    materials: ["100% Cotton Yarn", "Silver Keyring", "Daisy Accent Bead"],
    dimensions: "12 cm length",
    making_time: "2-3 business days",
    care_instructions: "Durable for daily pocket use.",
    customization_options: "Choose your 3 letters or full name + color option (Pastel Blue, Pink, Yellow, Mint).",
    shipping_info: "Glassine craft envelope with backing card.",
    story: "Handmade letter keychains designed to make your daily carries uniquely yours.",
    tags: ["Keychain", "Custom Name", "KGT", "Alphabet", "Handmade"],
    created_at: "2025-02-20T10:00:00Z",
    updated_at: "2025-02-25T10:00:00Z",
  },

  // ─── 6. SUNFLOWER KEYCHAIN ────────────────────────────────────────────────
  {
    id: "prod-6",
    slug: "sunflower-crochet-keychain",
    name: "Sunshine Sunflower Crochet Keychain",
    category: "keychains",
    collection_id: "col-3",
    short_description: "A cheerful hand-crocheted sunflower keychain with a golden yellow petal ring and rich dark brown center — pure sunshine in your pocket.",
    description: "Carry a little sunshine everywhere you go. This plump sunflower keychain is hand-crocheted petal by petal using bright golden yellow cotton yarn, with a deeply textured dark brown center in tight spiral stitches.",
    price: 299,
    is_available: true,
    is_featured: false,
    is_bestseller: true,
    is_new: false,
    is_published: true,
    images: [
      {
        id: "img-6-1",
        url: "/products/sunflower-keychain.jpg",
        alt: "Hand-crocheted golden sunflower keychain with silver ring",
        is_primary: true,
        order: 1,
      },
    ],
    materials: ["Mercerized Cotton Thread", "Silver Keyring", "Reinforced Cord"],
    dimensions: "5 cm diameter flower, 10 cm total hanging drop",
    making_time: "1-2 business days",
    care_instructions: "Durable for daily use. Hand wash with mild soap if needed.",
    customization_options: "Available with golden petals or pink butterfly style.",
    shipping_info: "Delivered in a mini glassine envelope with decorative twine.",
    story: "Simple, honest handmade happiness for everyday routines.",
    tags: ["Keychain", "Sunflower", "Pocket Art", "Under 500", "Best Seller"],
    created_at: "2025-02-05T10:00:00Z",
    updated_at: "2025-02-21T10:00:00Z",
  },
];

export const initialGalleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Handembroidered Handkerchief — BMW Logo & Bell Keychain Set",
    category: "Handkerchief Embroidery",
    image_url: "/products/handkerchief-bmw-embroidery.jpg",
    caption: "Bespoke BMW logo hand-stitched on pure white cotton handkerchief paired with a vintage bell keychain.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-2",
    likes_count: 540,
    created_at: "2025-02-15T10:00:00Z",
  },
  {
    id: "gal-2",
    title: "Handembroidered Handkerchief — Couple Hug Line Art & 'I LOVE U' Border",
    category: "Handkerchief Embroidery",
    image_url: "/products/handkerchief-iloveu-embroidery.jpg",
    caption: "Hand-embroidered couple hug line art with pink french knots and 'I LOVE U' sentiment border.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-1",
    likes_count: 610,
    created_at: "2025-02-17T10:00:00Z",
  },
  {
    id: "gal-3",
    title: "KGT Custom 3-Letter Crochet Name Keychain",
    category: "Keychains",
    image_url: "/products/kgt-crochet-keychain.jpg",
    caption: "3-letter custom name 'KGT' hand-crocheted in pastel blue yarn with white daisy accent.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-5",
    likes_count: 780,
    created_at: "2025-02-22T10:00:00Z",
  },
  {
    id: "gal-4",
    title: "A Bouquet That Never Fades",
    category: "Finished Pieces",
    image_url: "/products/orchid-bouquet-never-fades.jpg",
    caption: "Crochet orchid & daisy bouquet wrapped with gold satin ribbon.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-3",
    likes_count: 512,
    created_at: "2025-02-14T10:00:00Z",
  },
  {
    id: "gal-5",
    title: "Crochet Alphabet Keychain Template",
    category: "Keychains",
    image_url: "/products/alphabet-keychain-template.jpg",
    caption: "100% handmade letter keychains — custom initials, names, and words.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-5",
    likes_count: 689,
    created_at: "2025-02-18T10:00:00Z",
  },
  {
    id: "gal-6",
    title: "Crimson Rose Single Stem",
    category: "Packaging",
    image_url: "/products/red-rose-black-wrap.jpg",
    caption: "Single crimson rose in dramatic black parchment cone.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-4",
    likes_count: 420,
    created_at: "2025-02-20T10:00:00Z",
  },
  {
    id: "gal-7",
    title: "Sunshine Sunflower Keychain",
    category: "Keychains",
    image_url: "/products/sunflower-keychain.jpg",
    caption: "Pure sunshine in your pocket — hand-crocheted sunflower charm.",
    instagram_post_url: "https://instagram.com/artbythread.7",
    attached_product_id: "prod-6",
    likes_count: 390,
    created_at: "2025-03-01T10:00:00Z",
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: "test-1",
    customer_name: "Aanya S.",
    customer_location: "Mumbai",
    rating: 5,
    review: "I ordered the embroidered handkerchief with our line art and 'I LOVE U' border. It is so intimate, beautifully stitched, and came in a lovely wax-sealed envelope! 10/10 recommend!",
    product_name: "Couples Line Art Handkerchief",
    is_approved: true,
    created_at: "2025-02-12T10:00:00Z",
  },
  {
    id: "test-2",
    customer_name: "Harsh & Friends",
    customer_location: "Bengaluru",
    rating: 5,
    review: "The custom 'KGT' name keychain is incredible! Such fine detail, cute daisy accent, and solid quality. Everyone asks me where I got it.",
    product_name: "Custom Name Crochet Keychain",
    is_approved: true,
    created_at: "2025-02-18T10:00:00Z",
  },
  {
    id: "test-3",
    customer_name: "Pooja K.",
    customer_location: "New Delhi",
    rating: 5,
    review: "The custom BMW logo handkerchief set with the bell keychain was the best gift for my brother! The stitching is precise and tight.",
    product_name: "Custom Logo Handkerchief Set",
    is_approved: true,
    created_at: "2025-02-21T10:00:00Z",
  },
];

export const initialFAQs: FAQItem[] = [
  {
    id: "faq-1",
    question: "How do I place an order if there is no checkout cart?",
    answer: "Because every piece is handcrafted by hand in small batches, we handle orders personally through WhatsApp, Instagram DM, or Email! Simply click the 'Order on WhatsApp' or 'DM on Instagram' button on any creation page, and it will instantly open a chat with the creation's details pre-filled. We'll confirm your requirements, custom touches, timeline, and share payment details directly.",
    category: "Ordering & WhatsApp",
    order: 1,
    is_published: true,
  },
  {
    id: "faq-2",
    question: "How do custom handkerchief embroidery & name keychains work?",
    answer: "You can send us your photo, drawing, logo (like BMW or custom emblems), or name letters (like KGT). We sketch the digital layout, show thread color options, and estimate crafting time (usually 2 to 4 business days). Once approved, we hand-stitch your piece!",
    category: "Custom Requests",
    order: 2,
    is_published: true,
  },
  {
    id: "faq-3",
    question: "What materials do you use for handkerchiefs and keychains?",
    answer: "We strictly use 100% pure white cotton handkerchief fabric, DMC colorfast embroidery floss, soft milk cotton yarns, and sturdy metal keyrings.",
    category: "Care & Materials",
    order: 3,
    is_published: true,
  },
  {
    id: "faq-4",
    question: "Do you ship across India? How is it packaged?",
    answer: "Yes! We ship all across India via trusted courier partners. Every creation is carefully wrapped in aesthetic tissue and presented in a gift envelope or craft box with a handwritten note.",
    category: "Shipping & Timeline",
    order: 4,
    is_published: true,
  },
  {
    id: "faq-5",
    question: "How do I care for my embroidered handkerchief?",
    answer: "Gentle cold hand wash inside out with mild detergent. Air dry in shade, and iron on reverse using a cotton pressing cloth to preserve thread texture.",
    category: "Care & Materials",
    order: 5,
    is_published: true,
  },
];
